spring:
  application:
    name: tourisme_api
  datasource:
    url: jdbc:postgresql://localhost:5432/tourism
    username: abdoulaye
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    username: ablaye
    host: localhost
    password: password
    port: 1025
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9091/realms/tourism_app
  servlet:
    multipart:
      max-file-size: 50MB

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: tourisme-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


springdoc:
  default-produces-media-type: application/json

application:
  file:
    uploads:
      media-output-path: ./uploads